name: Upload Generated File to Azure Blob (Windows)

on:
  workflow_dispatch

jobs:
  upload-to-blob:
    runs-on: windows-latest
    steps:
      - name: Generate hello.txt
        shell: powershell
        run: |
          "Hello from GitHub Actions!" | Out-File -Encoding utf8 hello.txt

      - name: Upload file using AzCopy via Azure CLI (PowerShell)
        shell: powershell
        run: |
          Write-Host "Uploading to Azure Blob..."
          az storage azcopy blob upload `
            -s "hello.txt" `
            --destination "drivers/Chrome/beta/hello.txt" `
            -c windows `
            --connection-string "${{ secrets.PROD_HYP_MSFT_CONNECTION_STRING }}" `
            --recursive

          if ($LASTEXITCODE -ne 0) {
            Write-Host "Upload failed"
            exit 1
          } else {
            Write-Host "Upload succeeded"
          }
