name: Upload Generated File to Azure Blob

on:
  workflow_dispatch


jobs:
  upload-to-blob:
    runs-on: ubuntu-latest
    steps:
      # Install AzCopy
      - name: Check and Install AzCopy
        run: |
          if ! command -v azcopy &> /dev/null
          then
            wget https://aka.ms/downloadazcopy-v10-linux
            tar -xvf downloadazcopy-v10-linux
            sudo cp ./azcopy_linux_amd64_*/azcopy /usr/bin/
            rm -rf azcopy_linux_amd64_*
          else
            echo "AzCopy is already installed."
          fi

      - name: Generate hello.txt
        run: echo "Hello from GitHub Actions!" > hello.txt

      # Upload file using AzCopy
      - name: Upload file using Azure CLI (fallback)
        run: |
          az storage azcopy blob upload \
            -s "hello.txt" \
            --destination "drivers/Chrome/beta/hello.txt" \
            -c windows \
            --connection-string "BlobEndpoint=https://hypmsftprod1faf987b.blob.core.windows.net/;AccountName=hypmsftprod1faf987b;SharedAccessSignature=sv=2024-11-04&ss=b&srt=sco&sp=rwdlaciytfx&se=2025-04-11T22:22:10Z&st=2025-04-11T14:22:10Z&spr=https&sig=pzyxf7kfVDY1hDBxXEe%2F1JU8DGBtC0aiTGdH6wNIhTQ%3D" \
            --recursive
      
