name: Upload Generated File to Azure Blob (Windows PowerShell)

on:
  workflow_dispatch

jobs:
  upload-to-blob:
    runs-on: windows-latest

    steps:
      - name: Download and install AzCopy
        shell: powershell
        run: |
          Write-Host "Downloading AzCopy..."
          Invoke-WebRequest -Uri "https://aka.ms/downloadazcopy-v10-windows" -OutFile "azcopy.zip"
          Expand-Archive -Path "azcopy.zip" -DestinationPath "$env:TEMP\azcopy" -Force
          $azCopyPath = Get-ChildItem -Path "$env:TEMP\azcopy" -Recurse -Filter "azcopy.exe" | Select-Object -First 1
          $env:PATH += ";$($azCopyPath.DirectoryName)"
          Write-Host "AzCopy installed at: $($azCopyPath.FullName)"
          azcopy --version

      - name: Generate hello.txt
        shell: powershell
        run: |
          "Hello from GitHub Actions!" | Out-File -FilePath "hello.txt" -Encoding UTF8

      - name: Upload file using Azure CLI via PowerShell
        shell: powershell
        run: |
          Write-Host "Uploading hello.txt to Azure Blob..."
          $escapedString = $connectionString -replace '([;&=])', '`$1'
          az storage azcopy blob upload `
            -s "hello.txt" `
            --destination "drivers/Chrome/beta/hello.txt" `
            -c windows `
            --connection-string "$escapedString" `
            --recursive

          if ($LASTEXITCODE -ne 0) {
            Write-Host "Upload failed"
            exit 1
          } else {
            Write-Host "Upload succeeded"
          }
