name: Upload Generated File to Azure Blob

on:
  workflow_dispatch


jobs:
  upload-to-blob:
    runs-on: ubuntu-latest
    steps:
      # Install AzCopy
      - name: Install AzCopy
        run: |
          wget https://aka.ms/downloadazcopy-v10-linux
          tar -xzf downloadazcopy-v10-linux
          sudo cp azcopy_linux_amd64_*/azcopy /usr/local/bin/
          azcopy --version

      # Azure login (if needed for other steps)
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Upload file using AzCopy
      - name: Upload File to Azure Blob
        env:
          AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
        run: |
          azcopy copy \
            "/Users/deepanshuc/hello.txt" \
            "https://hypmsftprod1faf987b.blob.core.windows.net/drivers/Chrome/beta/hello.txt?${AZURE_STORAGE_CONNECTION_STRING}" \
            --overwrite=true
