name: Upload Generated File to Azure Blob

on:
  workflow_dispatch


jobs:
  upload-to-blob:
    runs-on: ubuntu-latest
    steps:
      # Install AzCopy
      - name: Install AzCopy
        run: |
          wget https://aka.ms/downloadazcopy-v10-linux
          tar -xzf downloadazcopy-v10-linux
          sudo cp azcopy_linux_amd64_*/azcopy /usr/local/bin/
          azcopy --version

      - name: Generate hello.txt
        run: echo "Hello from GitHub Actions!" > hello.txt

      # Upload file using AzCopy
      - name: Upload file using AzCopy
        run: |
          # Adjust the source path if the file is not in the repo root
          az storage azcopy blob upload \
            -s "hello.txt" \  # Path to your file in the workflow's context
            --destination "drivers/Chrome/beta/hello.txt" \
            -c "windows" \  # Container name
            --connection-string ${{secrets.PROD_HYP_MSFT_CONNECTION_STRING}}
