name: Upload Generated File to Azure Blob

on:
  workflow_dispatch


jobs:
  upload-to-blob:
    runs-on: ubuntu-latest
    steps:
      # Install AzCopy
      - name: Check and Install AzCopy
        run: |
          if ! command -v azcopy &> /dev/null
          then
            wget https://aka.ms/downloadazcopy-v10-linux
            tar -xvf downloadazcopy-v10-linux
            sudo cp ./azcopy_linux_amd64_*/azcopy /usr/bin/
            rm -rf azcopy_linux_amd64_*
          else
            echo "AzCopy is already installed."
          fi

      - name: Generate hello.txt
        run: echo "Hello from GitHub Actions!" > hello.txt

      # Upload file using AzCopy
      - name: Upload file using Azure CLI (fallback)
        run: |
          az storage blob upload \
            --file hello.txt \
            --container-name windows \
            --name drivers/Chrome/beta/hello.txt \
            --connection-string ${{ secrets.PROD_HYP_MSFT_CONNECTION_STRING }}
            --overwrite true

      
